---
  FINNHUB_KEY1: "API_KEY_HERE"
  FINNHUB_KEY2: "API_KEY_HERE"

  TWITTER_BEARER_TOKEN: "API_KEY_HERE"

  API_REDDIT_CLIENT_ID: "API_KEY_HERE"
  API_REDDIT_CLIENT_SECRET: "API_KEY_HERE"
  API_REDDIT_USER_AGENT:  "subreddit_scraper"

  GMAIL_SENDER_EMAIL: "API_KEY_HERE"
  GMAIL_SENDER_PASSWORD: "API_KEY_HERE"

