FINNHUB_KEY1: c3k54riad3i8d96rsqe0
GMAIL_SENDER_EMAIL: API_KEY_HERE
GMAIL_SENDER_PASSWORD: API_KEY_HERE
IS_LOCALLY_HOSTED: true
MYSQL_DATABASE: stocksera_test
MYSQL_HOST: localhost
MYSQL_PASSWORD: admin
MYSQL_PORT: '3306'
MYSQL_USER: root
POLYGON_KEY: RZ5n_HYpq1lpX6tPPoU2CJCQ8cjdKXp3
REDDIT_CLIENT_ID: 3RbFQX8O9UqDCA
REDDIT_CLIENT_SECRET: NalOX_ZQqGWP4eYKZv6bPlAb2aWOcA
REDDIT_USER_AGENT: subreddit_scraper
STOCKSERA_API: '12345'
STOCKSERA_BASE_URL: http://127.0.0.1:8000/api
TWITTER_BEARER_TOKEN: AAAAAAAAAAAAAAAAAAAAAIJtSwEAAAAAVP9%2BmlfK4v97TYsn1XKthfgh6q0%3DWyqQcbXlGE9h6ZiTmgGvw9EhgvpRYXTdrQVYdT0Bm6SVBTPIVQ
WHALE_ALERT: 1HDED9FmqwF6WPFNDrbRBZTazQeRxX8t
