FINNHUB_KEY1: API_KEY_HERE
FINNHUB_KEY2: API_KEY_HERE
GMAIL_SENDER_EMAIL: API_KEY_HERE
GMAIL_SENDER_PASSWORD: API_KEY_HERE
IS_LOCALLY_HOSTED: true
MYSQL_DATABASE: API_KEY_HERE
MYSQL_HOST: API_KEY_HERE
MYSQL_PASSWORD: API_KEY_HERE
MYSQL_PORT: API_KEY_HERE
MYSQL_USER: API_KEY_HERE
POLYGON_KEY: API_KEY_HERE
REDDIT_CLIENT_ID: API_KEY_HERE
REDDIT_CLIENT_SECRET: API_KEY_HERE
REDDIT_USER_AGENT: subreddit_scraper
STOCKSERA_API: API_KEY_HERE
STOCKSERA_BASE_URL: http://127.0.0.1:8000/api
TDA_ACCESS_TOKEN: API_KEY_HERE
TDA_CLIENT_ID: API_KEY_HERE
TDA_REFRESH_TOKEN: API_KEY_HERE
TWITTER_BEARER_TOKEN: API_KEY_HERE
WHALE_ALERT: API_KEY_HERE
