---
  # https://finnhub.io/
  FINNHUB_KEY1: "API_KEY_HERE"
  FINNHUB_KEY2: "API_KEY_HERE"

  # https://developer.twitter.com/en/portal/dashboard/
  TWITTER_BEARER_TOKEN: "API_KEY_HERE"

  # https://www.reddit.com/prefs/apps/
  API_REDDIT_CLIENT_ID: "API_KEY_HERE"
  API_REDDIT_CLIENT_SECRET: "API_KEY_HERE"
  API_REDDIT_USER_AGENT:  "subreddit_scraper"

  # https://api.whale-alert.io/
  API_WHALE_ALERT: "API_KEY_HERE"

  # https://realpython.com/python-send-email/
  GMAIL_SENDER_EMAIL: "API_KEY_HERE"
  GMAIL_SENDER_PASSWORD: "API_KEY_HERE"

  # mysql credentials
  MYSQL_USER: "root"
  MYSQL_PASSWORD: "admin"
  MYSQL_HOST: "127.0.0.1"
  MYSQL_DATABASE: "stocksera"